
name: Build & Test rulyotano.match

on:
  pull_request:
    branches: 
      - main
    paths:
      - src/rulyotano.math/**

jobs:
  publish:
      uses: ./.github/workflows/build-test.yml
      with:
        path: ${{ github.workspace }}/src/rulyotano.math