
name: Npm publish rulyotano.match

on:
  push:
    branches: 
      - main
    paths:
      - rulyotano.math/**

jobs:
  publish:
      uses: ./.github/workflows/npm-publish.yml
      with:
        path: ./src/rulyotano.math
