name: rulyotano.math - Publish

on:
  push:
    branches: 
      - main
    paths:
      - src/rulyotano.math/package.json

jobs:
  publish:
      uses: ./.github/workflows/npm-publish.yml
      with:
        path: ./src/rulyotano.math
      secrets: inherit
